# 使用sklearn中自带的KDTree实现KD树最近邻搜索

In [2]:
from sklearn import datasets
from sklearn.neighbors import KDTree, KNeighborsClassifier, KNeighborsTransformer
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### 加载数据集

In [3]:
dataSet = pd.read_excel(r'D:\a学业信计\a研究生\数据集\西瓜书\watermelon4.0.xlsx')
data = dataSet.values
labels = dataSet.columns.values
indexs = dataSet.index.values

In [5]:
from sklearn import datasets

In [6]:
X, y = datasets.load_iris(return_X_y=True)

In [10]:
tree = KDTree(X)

In [13]:
dist_to_knn, idx_of_knn = tree.query(X = X[[3]], k = 5)

In [22]:
X[[3]]

array([[4.6, 3.1, 1.5, 0.2]])

In [14]:
print(dist_to_knn)

[[0.         0.14142136 0.17320508 0.2236068  0.24494897]]


In [16]:
X[idx_of_knn]

array([[[4.6, 3.1, 1.5, 0.2],
        [4.6, 3.2, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [4.7, 3.2, 1.3, 0.2]]])

In [18]:
tree_1 = KDTree(data)

In [23]:
data[[1]]

array([[0.403, 0.237]])

In [24]:
dist, index = tree_1.query(data[[1]], k = 3)

In [25]:
print(dist, index)

[[0.         0.04280187 0.06412488]] [[ 1 13 21]]


In [26]:
data[index]

array([[[0.403, 0.237],
        [0.437, 0.211],
        [0.339, 0.241]]])

# 使用sklearn中自带的BallTree实现检索

In [28]:
from sklearn.neighbors import BallTree

In [29]:
tree_2 = BallTree(data)

In [30]:
data[[1]]

array([[0.403, 0.237]])

In [32]:
dist_2, index_2 = tree_2.query(data[[1]], k = 3)

In [ ]:
print(dist)